import { isSellerPanel } from "./panelConfig";

export const API_PREFIX = "/api/v1";

const byPanel = (adminPath, sellerPath = adminPath) =>
  (isSellerPanel() ? sellerPath : adminPath);

const byPanelFn = (adminBuilder, sellerBuilder = adminBuilder) => (...args) =>
  (isSellerPanel() ? sellerBuilder(...args) : adminBuilder(...args));

export const ENDPOINTS = {
  meta: {
    dropdown: (resource) => `/meta/dropdowns/${resource}`,
  },
  auth: {
    register: "/auth/register",
    login: "/auth/login",
    social: "/auth/social",
    status: "/auth/status",
    refresh: "/auth/refresh",
    me: "/users/me",
    forgotPassword: "/auth/forgot-password",
    sendOtp: "/auth/send-otp",
    verifyOtp: "/auth/verify-otp",
    resendOtp: "/auth/resend-otp",
    resetPassword: "/auth/reset-password",
    changePassword: "/auth/change-password",
    registerOtp: "/auth/register-otp",
    verifyRegistration: "/auth/verify-registration",
  },
  dashboard: {
    overview: byPanel("/admin/dashboard/overview", "/sellers/me/dashboard"),
  },
  users: {
    adminUsers: "/admin/users",
    adminUser: (userId) => `/admin/users/${userId}`,
    myAddresses: "/users/me/addresses",
    myAddress: (addressId) => `/users/me/addresses/${addressId}`,
  },
  adminAccess: {
    modules: byPanel("/admin/access/modules", "/sellers/me/access/modules"),
    admins: "/admin/access/admins",
    subAdmins: byPanel("/admin/access/sub-admins", "/sellers/me/sub-admins"),
    subAdminModules: byPanelFn(
      (userId) => `/admin/access/sub-admins/${userId}/modules`,
      (userId) => `/sellers/me/sub-admins/${userId}/modules`
    ),
  },
  sellerUsers: {
    sellers: "/admin/seller-users/sellers",
    sellerAdmins: "/admin/seller-users/seller-admins",
    sellerSubAdmins: "/admin/seller-users/seller-sub-admins",
    createSellerAdmin: "/admin/seller-users/seller-admin",
    createSellerSubAdmin: "/admin/seller-users/seller-sub-admin",
  },
  sellers: {
    onboardingKyc: "/sellers/onboarding/kyc",
    onboardingProfile: "/sellers/onboarding/profile",
    vendors: "/admin/vendors",
    list: "/admin/sellers",
    detail: (sellerId) => `/admin/sellers/${sellerId}`,
    vendorStatus: (sellerId) => `/admin/vendors/${sellerId}/status`,
    adminStatus: (sellerId) => `/admin/sellers/${sellerId}/status`,
    kycStatus: (sellerId) => `/admin/sellers/${sellerId}/kyc/status`,
    kycDetail: (sellerId) => `/admin/sellers/${sellerId}/kyc`,
    bankStatus: (sellerId) => `/admin/sellers/${sellerId}/bank/status`,
    onboardingStatus: (sellerId) => `/admin/sellers/${sellerId}/onboarding/status`,
    goLive: (sellerId) => `/admin/sellers/${sellerId}/go-live`,
    kycReview: (sellerId) => `/sellers/${sellerId}/kyc/review`,
    kycReviewAdmin: (sellerId) => `/admin/sellers/${sellerId}/kyc/status`,
    myStatus: "/sellers/me/status",
    myKyc: "/sellers/me/kyc",
    sellerOnboardingStatus: "/sellers/me/onboarding-status",
    approvalModalSeen: "/sellers/me/onboarding/approval-modal-seen",
    tracking: "/sellers/me/tracking",
    trackingOrder: (orderId) => `/sellers/me/tracking/${orderId}`,
    profile: "/sellers/me/profile",
    businessAddress: "/sellers/me/business-address",
    pickupAddress: "/sellers/me/pickup-address",
    bankDetails: "/sellers/me/bank-details",
    moreInfo: "/sellers/me/more-info",
    settings: "/sellers/me/settings",
    dashboard: "/sellers/me/dashboard",
    subAdmins: "/sellers/me/sub-admins",
    subAdminModules: (userId) => `/sellers/me/sub-admins/${userId}/modules`,
    subAdminStatus: (userId) => `/sellers/me/sub-admins/${userId}/status`,
    subAdmin: (userId) => `/sellers/me/sub-admins/${userId}`,
  },
  products: {
    list: byPanel("/admin/products", "/products"),
    listForPanel: byPanel("/admin/products", "/products/seller/me"),
    search: "/products/search",
    sellerMine: "/products/seller/me",
    detail: byPanelFn(
      (productId) => `/admin/products/${productId}`,
      (productId) => `/products/${productId}`
    ),
    moderationQueue: "/admin/products/moderation-queue",
    moderate: (productId) => `/admin/products/${productId}/moderate`,
    approve: (productId) => `/admin/products/${productId}/approve`,
    reject: (productId) => `/admin/products/${productId}/reject`,
    status: (productId) => `/admin/products/${productId}/status`,
    bulkUpdate: "/admin/products/bulk/update",
    inventory: (productId) => `/admin/products/${productId}/inventory`,
    inventoryStats: "/admin/products/inventory/stats",
    analyticsTop: "/admin/products/analytics/top",
  },
  orders: {
    admin: "/admin/orders",
    mine: "/orders/me",
    sellerMine: "/orders/seller/me",
    listForPanel: byPanel("/admin/orders", "/orders/seller/me"),
    create: "/orders",
    detail: (orderId) => `/orders/${orderId}`,
    cancel: (orderId) => `/orders/${orderId}/cancel`,
    status: (orderId) => `/orders/${orderId}/status`,
  },
  payments: {
    admin: "/admin/payments",
  },
  payouts: {
    admin: "/admin/payouts",
    myCommissions: "/sellers/commissions/my-commissions",
    myPayouts: "/sellers/commissions/my-payouts",
    calculate: (orderId) => `/sellers/commissions/calculate/${orderId}`,
    process: "/sellers/commissions/process-payouts",
    settlements: "/sellers/commissions/settlements",
  },
  referral: {
    influencers: "/admin/referral/influencers",
    parentInfluencers: "/admin/referral/influencers/parents",
    childInfluencers: (parentId) => `/admin/referral/influencers/${parentId}/children`,
    influencerStatus: (influencerId) => `/admin/referral/influencers/${influencerId}/status`,
    promoteInfluencer: (influencerId) => `/admin/referral/influencers/${influencerId}/promote`,
    codes: "/admin/referral/codes",
    code: (codeId) => `/admin/referral/codes/${codeId}`,
    orders: "/admin/referral/orders",
    commissions: "/admin/referral/commissions",
    payouts: "/admin/referral/payouts",
    approvePayout: (payoutId) => `/admin/referral/payouts/${payoutId}/approve`,
    rejectPayout: (payoutId) => `/admin/referral/payouts/${payoutId}/reject`,
    paidPayout: (payoutId) => `/admin/referral/payouts/${payoutId}/paid`,
    rules: "/admin/referral/rules",
    summary: "/admin/referral/reports/summary",
    hierarchy: "/admin/referral/reports/hierarchy",
    fraud: "/admin/referral/fraud",
  },
  tax: {
    adminReports: "/admin/tax/reports",
    adminInvoice: (orderId) => `/admin/tax/orders/${orderId}/invoice`,
    invoice: (orderId) => `/tax/orders/${orderId}/invoice`,
    reports: "/tax/reports",
  },
  coupons: {
    list: "/pricing/coupons",
    detail: (couponId) => `/pricing/coupons/${couponId}`,
  },
  delivery: {
    serviceability: "/delivery/serviceability",
    orderEwayBill: (orderId) => `/delivery/orders/${orderId}/eway-bill`,
    ewayBillStatus: (ewayBillId) => `/delivery/eway-bills/${ewayBillId}/status`,
  },
  returns: {
    byOrder: (orderId) => `/returns/order/${orderId}`,
    mine: "/returns/my-returns",
    approve: (returnId) => `/returns/${returnId}/approve`,
    refund: (returnId) => `/returns/${returnId}/refund`,
    analytics: "/admin/returns/analytics",
  },
  notifications: {
    mine: "/notifications/me",
    preferences: "/notifications/preferences",
  },
  analytics: {
    seller: "/analytics",
    realtime: "/admin/analytics/realtime",
    returns: "/admin/returns/analytics",
    chargebacks: "/admin/chargebacks",
  },
  rbac: {
    permissionManagementModules: "/rbac/permission-management/modules",
    modules: "/rbac/modules",
    sidebarModules: "/rbac/modules/sidebar",
    module: (moduleId) => `/rbac/modules/${moduleId}`,
    moduleStatus: (moduleId) => `/rbac/modules/${moduleId}/status`,
    reorderModules: "/rbac/modules/reorder",
    permissions: "/rbac/permissions",
    permission: (permissionId) => `/rbac/permissions/${permissionId}`,
    roles: "/rbac/roles",
    role: (roleId) => `/rbac/roles/${roleId}`,
    rolePermissions: (roleId) => `/rbac/roles/${roleId}/permissions`,
    rolePermissionsBulk: (roleId) => `/rbac/roles/${roleId}/permissions/bulk`,
    userPermissions: (userId) => `/rbac/users/${userId}/permissions`,
    userEffectivePermissions: (userId) => `/rbac/users/${userId}/permissions/effective`,
    userPermissionCheck: (userId) => `/rbac/users/${userId}/permissions/check`,
    userPermissionsBulk: (userId) => `/rbac/users/${userId}/permissions/bulk`,
    userRoles: (userId) => `/rbac/users/${userId}/roles`,
    userRoleCheck: (userId) => `/rbac/users/${userId}/roles/check`,
    userRolesBulk: (userId) => `/rbac/users/${userId}/roles/bulk`,
  },
  platform: {
    apiKeys: "/admin/platform/api-keys",
    webhooks: "/admin/platform/webhooks",
    featureFlags: "/admin/platform/feature-flags",
    subscriptionPlans: "/admin/platform/subscription-plans",
    subscriptionPlan: (planId) => `/admin/platform/subscription-plans/${planId}`,
    subscriptions: "/admin/platform/subscriptions",
    subscriptionStatus: (subscriptionId) => `/admin/platform/subscriptions/${subscriptionId}/status`,
    feeConfig: "/admin/platform/fee-config",
    feeConfigDetail: (configId) => `/admin/platform/fee-config/${configId}`,
    categories: "/admin/platform/categories",
    category: (categoryKey) => `/admin/platform/categories/${categoryKey}`,
    categoryAttributes: (categoryKey) => `/admin/categories/${categoryKey}/attributes`,
    productFamilies: "/admin/platform/product-families",
    productFamily: (familyCode) => `/admin/platform/product-families/${familyCode}`,
    productVariants: "/admin/platform/product-variants",
    productVariant: (variantId) => `/admin/platform/product-variants/${variantId}`,
    brands: "/admin/platform/brands",
    brand: (brandId) => `/admin/platform/brands/${brandId}`,
    warrantyTemplates: "/admin/platform/warranty-templates",
    warrantyTemplate: (templateId) => `/admin/platform/warranty-templates/${templateId}`,
    finishes: "/admin/platform/finishes",
    finish: (finishId) => `/admin/platform/finishes/${finishId}`,
    dimensions: "/admin/platform/dimensions",
    dimension: (dimensionId) => `/admin/platform/dimensions/${dimensionId}`,
    batches: "/admin/platform/batches",
    batch: (batchId) => `/admin/platform/batches/${batchId}`,
    productOptions: "/admin/platform/product-options",
    productOption: (optionId) => `/admin/platform/product-options/${optionId}`,
    productOptionValues: "/admin/platform/product-option-values",
    productOptionValue: (optionValueId) => `/admin/platform/product-option-values/${optionValueId}`,
    hsnCodes: "/admin/platform/hsn-codes",
    hsnCode: (hsnCode) => `/admin/platform/hsn-codes/${hsnCode}`,
    geography: "/admin/platform/geography",
    geographyDetail: (countryCode) => `/admin/platform/geography/${countryCode}`,
    contentPages: "/admin/cms",
    contentPage: (slug) => `/admin/cms/${slug}`,
    productReviews: "/admin/platform/product-reviews",
    productReview: (reviewId) => `/admin/platform/product-reviews/${reviewId}`,
  },
  common: {
    countries: "/admin/common/countries",
    country: (countryId) => `/admin/common/countries/${countryId}`,
    countryStatus: "/admin/common/countries/status",
    states: "/admin/common/states",
    state: (stateId) => `/admin/common/states/${stateId}`,
    stateStatus: "/admin/common/states/status",
    cities: "/admin/common/cities",
    city: (cityId) => `/admin/common/cities/${cityId}`,
    cityStatus: "/admin/common/cities/status",
    zipCodes: "/admin/common/zip-codes",
    zipCode: (zipCodeId) => `/admin/common/zip-codes/${zipCodeId}`,
    zipCodeStatus: "/admin/common/zip-codes/status",
    taxes: "/admin/common/taxes",
    tax: (taxId) => `/admin/common/taxes/${taxId}`,
    taxStatus: "/admin/common/taxes/status",
    subTaxes: "/admin/common/sub-taxes",
    subTax: (subTaxId) => `/admin/common/sub-taxes/${subTaxId}`,
    subTaxStatus: "/admin/common/sub-taxes/status",
    taxRules: "/admin/common/tax-rules",
    taxRule: (taxRuleId) => `/admin/common/tax-rules/${taxRuleId}`,
    taxRuleStatus: "/admin/common/tax-rules/status",
  },
  system: {
    health: "/admin/system/health",
    queues: "/admin/system/queues",
    pauseQueue: (queueName) => `/admin/system/queues/${queueName}/pause`,
    resumeQueue: (queueName) => `/admin/system/queues/${queueName}/resume`,
    deadLetter: "/admin/system/dead-letter",
    retryDeadLetter: (eventId) => `/admin/system/dead-letter/${eventId}/retry`,
    discardDeadLetter: (eventId) => `/admin/system/dead-letter/${eventId}/discard`,
  },
};
