export const API_PREFIX = "/api/v1";

const withPrefix = (path) => `${API_PREFIX}${path}`;

export const toRelativeApiPath = (endpoint = "") => {
  if (!endpoint) return endpoint;
  return endpoint.startsWith(API_PREFIX)
    ? endpoint.slice(API_PREFIX.length) || "/"
    : endpoint;
};

export const USER_ROLES = [
  "admin",
  "sub-admin",
  "seller",
  "seller-sub-admin",
  "buyer",
  "super-admin",
];

export const ACCOUNT_STATUSES = [
  "active",
  "suspended",
  "pending_approval",
];

export const SELLER_ONBOARDING_STATUSES = [
  "initiated",
  "in_progress",
  "under_review",
  "ready_for_go_live",
  "rejected",
];

export const PRODUCT_STATUSES = [
  "draft",
  "pending_approval",
  "active",
  "inactive",
  "rejected",
];

export const ORDER_STATUSES = [
  "pending_payment",
  "payment_failed",
  "confirmed",
  "packed",
  "shipped",
  "delivered",
  "return_requested",
  "returned",
  "cancelled",
  "fulfilled",
];

export const PAYMENT_STATUSES = [
  "initiated",
  "authorized",
  "captured",
  "failed",
  "refunded",
];

export const DELIVERY_STATUSES = [
  "not_created",
  "initiated",
  "manifested",
  "picked_up",
  "in_transit",
  "out_for_delivery",
  "delivered",
  "failed",
  "cancelled",
];

export const KYC_REVIEW_STATUSES = [
  "under_review",
  "verified",
  "rejected",
];

export const PLATFORM_MODULES = [
  "users",
  "products",
  "carts",
  "orders",
  "payments",
  "platform",
  "sellers",
  "notifications",
  "analytics",
  "pricing",
  "wallets",
  "tax",
  "subscriptions",
  "rbac",
  "warranty",
  "loyalty",
  "recommendations",
  "returns",
  "fraud",
  "dynamic-pricing",
  "delivery",
  "admin",
];

export const SELLER_MODULES = [
  "products",
  "orders",
  "pricing",
  "notifications",
  "analytics",
  "sellers",
  "sellers/commissions",
  "returns",
  "delivery",
];

export const authEndpoints = {
  register: withPrefix("/auth/register"),
  registerOtp: withPrefix("/auth/register-otp"),
  verifyRegistration: withPrefix("/auth/verify-registration"),
  login: withPrefix("/auth/login"),
  social: withPrefix("/auth/social"),
  status: withPrefix("/auth/status"),
  refresh: withPrefix("/auth/refresh"),
  me: withPrefix("/users/me"),
  forgotPassword: withPrefix("/auth/forgot-password"),
  sendOtp: withPrefix("/auth/send-otp"),
  verifyOtp: withPrefix("/auth/verify-otp"),
  resendOtp: withPrefix("/auth/resend-otp"),
  resetPassword: withPrefix("/auth/reset-password"),
  changePassword: withPrefix("/auth/change-password"),
};

export const adminEndpoints = {
  accessModules: withPrefix("/admin/access/modules"),
  admins: withPrefix("/admin/access/admins"),
  subAdmins: withPrefix("/admin/access/sub-admins"),
  subAdminModules: (userId) => withPrefix(`/admin/access/sub-admins/${userId}/modules`),
  dashboardOverview: withPrefix("/admin/dashboard/overview"),
  users: withPrefix("/admin/users"),
  userById: (userId) => withPrefix(`/admin/users/${userId}`),
  vendors: withPrefix("/admin/vendors"),
  vendorStatus: (sellerId) => withPrefix(`/admin/vendors/${sellerId}/status`),
  moderationQueue: withPrefix("/admin/products/moderation-queue"),
  moderateProduct: (productId) => withPrefix(`/admin/products/${productId}/moderate`),
  orders: withPrefix("/admin/orders"),
  payments: withPrefix("/admin/payments"),
  payouts: withPrefix("/admin/payouts"),
  taxReports: withPrefix("/admin/tax/reports"),
  invoice: (orderId) => withPrefix(`/admin/tax/orders/${orderId}/invoice`),
  apiKeys: withPrefix("/admin/platform/api-keys"),
  webhooks: withPrefix("/admin/platform/webhooks"),
  featureFlags: withPrefix("/admin/platform/feature-flags"),
  realtimeAnalytics: withPrefix("/admin/analytics/realtime"),
  returnsAnalytics: withPrefix("/admin/returns/analytics"),
  chargebacks: withPrefix("/admin/chargebacks"),
  systemHealth: withPrefix("/admin/system/health"),
  queues: withPrefix("/admin/system/queues"),
  pauseQueue: (queueName) => withPrefix(`/admin/system/queues/${queueName}/pause`),
  resumeQueue: (queueName) => withPrefix(`/admin/system/queues/${queueName}/resume`),
  deadLetter: withPrefix("/admin/system/dead-letter"),
  retryDeadLetter: (eventId) => withPrefix(`/admin/system/dead-letter/${eventId}/retry`),
  discardDeadLetter: (eventId) => withPrefix(`/admin/system/dead-letter/${eventId}/discard`),
  subscriptionPlans: withPrefix("/admin/platform/subscription-plans"),
  subscriptionPlanById: (planId) => withPrefix(`/admin/platform/subscription-plans/${planId}`),
  platformSubscriptions: withPrefix("/admin/platform/subscriptions"),
  platformSubscriptionStatus: (subscriptionId) =>
    withPrefix(`/admin/platform/subscriptions/${subscriptionId}/status`),
  feeConfig: withPrefix("/admin/platform/fee-config"),
  feeConfigById: (configId) => withPrefix(`/admin/platform/fee-config/${configId}`),
  categories: withPrefix("/admin/platform/categories"),
  categoryByKey: (categoryKey) => withPrefix(`/admin/platform/categories/${categoryKey}`),
  productFamilies: withPrefix("/admin/platform/product-families"),
  productFamilyByCode: (familyCode) => withPrefix(`/admin/platform/product-families/${familyCode}`),
  productVariants: withPrefix("/admin/platform/product-variants"),
  productVariantById: (variantId) => withPrefix(`/admin/platform/product-variants/${variantId}`),
  hsnCodes: withPrefix("/admin/platform/hsn-codes"),
  hsnCodeByCode: (hsnCode) => withPrefix(`/admin/platform/hsn-codes/${hsnCode}`),
  geography: withPrefix("/admin/platform/geography"),
  geographyByCode: (countryCode) => withPrefix(`/admin/platform/geography/${countryCode}`),
  contentPages: withPrefix("/admin/platform/content-pages"),
  contentPageBySlug: (slug) => withPrefix(`/admin/platform/content-pages/${slug}`),
};

export const sellerEndpoints = {
  onboardingKyc: withPrefix("/sellers/onboarding/kyc"),
  onboardingProfile: withPrefix("/sellers/onboarding/profile"),
  reviewKyc: (sellerId) => withPrefix(`/sellers/${sellerId}/kyc/review`),
  status: withPrefix("/sellers/me/status"),
  tracking: withPrefix("/sellers/me/tracking"),
  trackingOrder: (orderId) => withPrefix(`/sellers/me/tracking/${orderId}`),
  profile: withPrefix("/sellers/me/profile"),
  businessAddress: withPrefix("/sellers/me/business-address"),
  pickupAddress: withPrefix("/sellers/me/pickup-address"),
  bankDetails: withPrefix("/sellers/me/bank-details"),
  moreInfo: withPrefix("/sellers/me/more-info"),
  settings: withPrefix("/sellers/me/settings"),
  dashboard: withPrefix("/sellers/me/dashboard"),
  accessModules: withPrefix("/sellers/me/access/modules"),
  subAdmins: withPrefix("/sellers/me/sub-admins"),
  subAdminModules: (userId) => withPrefix(`/sellers/me/sub-admins/${userId}/modules`),
};

export const sellerCommissionEndpoints = {
  myCommissions: withPrefix("/sellers/commissions/my-commissions"),
  myPayouts: withPrefix("/sellers/commissions/my-payouts"),
  calculate: (orderId) => withPrefix(`/sellers/commissions/calculate/${orderId}`),
  processPayouts: withPrefix("/sellers/commissions/process-payouts"),
  settlements: withPrefix("/sellers/commissions/settlements"),
};

export const authApiMap = [
  ["register", "POST", authEndpoints.register],
  ["registerOtp", "POST", authEndpoints.registerOtp],
  ["verifyRegistration", "POST", authEndpoints.verifyRegistration],
  ["login", "POST", authEndpoints.login],
  ["social", "POST", authEndpoints.social],
  ["status", "GET", authEndpoints.status],
  ["refresh", "POST", authEndpoints.refresh],
  ["me", "GET", authEndpoints.me],
  ["forgotPassword", "POST", authEndpoints.forgotPassword],
  ["sendOtp", "POST", authEndpoints.sendOtp],
  ["verifyOtp", "POST", authEndpoints.verifyOtp],
  ["resendOtp", "POST", authEndpoints.resendOtp],
  ["resetPassword", "POST", authEndpoints.resetPassword],
  ["changePassword", "POST", authEndpoints.changePassword],
];

export const adminApiMap = [
  ["listAccessModules", "GET", adminEndpoints.accessModules],
  ["createAdmin", "POST", adminEndpoints.admins],
  ["listAdmins", "GET", adminEndpoints.admins],
  ["createPlatformSubAdmin", "POST", adminEndpoints.subAdmins],
  ["listPlatformSubAdmins", "GET", adminEndpoints.subAdmins],
  ["updatePlatformSubAdminModules", "PATCH", adminEndpoints.subAdminModules],
  ["dashboardOverview", "GET", adminEndpoints.dashboardOverview],
  ["listUsers", "GET", adminEndpoints.users],
  ["getUserDetail", "GET", adminEndpoints.userById],
  ["updateUser", "PATCH", adminEndpoints.userById],
  ["deactivateUser", "DELETE", adminEndpoints.userById],
  ["listVendors", "GET", adminEndpoints.vendors],
  ["updateVendorStatus", "PATCH", adminEndpoints.vendorStatus],
  ["productModerationQueue", "GET", adminEndpoints.moderationQueue],
  ["moderateProduct", "PATCH", adminEndpoints.moderateProduct],
  ["listOrders", "GET", adminEndpoints.orders],
  ["listPayments", "GET", adminEndpoints.payments],
  ["createPayout", "POST", adminEndpoints.payouts],
  ["listPayouts", "GET", adminEndpoints.payouts],
  ["taxReports", "GET", adminEndpoints.taxReports],
  ["generateInvoice", "POST", adminEndpoints.invoice],
  ["createApiKey", "POST", adminEndpoints.apiKeys],
  ["listApiKeys", "GET", adminEndpoints.apiKeys],
  ["createWebhook", "POST", adminEndpoints.webhooks],
  ["listWebhooks", "GET", adminEndpoints.webhooks],
  ["upsertFeatureFlag", "PUT", adminEndpoints.featureFlags],
  ["listFeatureFlags", "GET", adminEndpoints.featureFlags],
  ["realtimeAnalytics", "GET", adminEndpoints.realtimeAnalytics],
  ["returnsAnalytics", "GET", adminEndpoints.returnsAnalytics],
  ["listChargebacks", "GET", adminEndpoints.chargebacks],
  ["systemHealth", "GET", adminEndpoints.systemHealth],
  ["queueStatus", "GET", adminEndpoints.queues],
  ["pauseQueue", "POST", adminEndpoints.pauseQueue],
  ["resumeQueue", "POST", adminEndpoints.resumeQueue],
  ["listDeadLetterEvents", "GET", adminEndpoints.deadLetter],
  ["retryDeadLetterEvent", "POST", adminEndpoints.retryDeadLetter],
  ["discardDeadLetterEvent", "POST", adminEndpoints.discardDeadLetter],
  ["createSubscriptionPlan", "POST", adminEndpoints.subscriptionPlans],
  ["listSubscriptionPlans", "GET", adminEndpoints.subscriptionPlans],
  ["getSubscriptionPlan", "GET", adminEndpoints.subscriptionPlanById],
  ["updateSubscriptionPlan", "PATCH", adminEndpoints.subscriptionPlanById],
  ["deleteSubscriptionPlan", "DELETE", adminEndpoints.subscriptionPlanById],
  ["listPlatformSubscriptions", "GET", adminEndpoints.platformSubscriptions],
  ["updatePlatformSubscriptionStatus", "PATCH", adminEndpoints.platformSubscriptionStatus],
  ["createPlatformFeeConfig", "POST", adminEndpoints.feeConfig],
  ["listPlatformFeeConfigs", "GET", adminEndpoints.feeConfig],
  ["getPlatformFeeConfig", "GET", adminEndpoints.feeConfigById],
  ["updatePlatformFeeConfig", "PATCH", adminEndpoints.feeConfigById],
  ["deletePlatformFeeConfig", "DELETE", adminEndpoints.feeConfigById],
  ["createCategory", "POST", adminEndpoints.categories],
  ["listCategories", "GET", adminEndpoints.categories],
  ["getCategory", "GET", adminEndpoints.categoryByKey],
  ["updateCategory", "PATCH", adminEndpoints.categoryByKey],
  ["deleteCategory", "DELETE", adminEndpoints.categoryByKey],
  ["createProductFamily", "POST", adminEndpoints.productFamilies],
  ["listProductFamilies", "GET", adminEndpoints.productFamilies],
  ["getProductFamily", "GET", adminEndpoints.productFamilyByCode],
  ["updateProductFamily", "PATCH", adminEndpoints.productFamilyByCode],
  ["deleteProductFamily", "DELETE", adminEndpoints.productFamilyByCode],
  ["createProductVariant", "POST", adminEndpoints.productVariants],
  ["listProductVariants", "GET", adminEndpoints.productVariants],
  ["getProductVariant", "GET", adminEndpoints.productVariantById],
  ["updateProductVariant", "PATCH", adminEndpoints.productVariantById],
  ["deleteProductVariant", "DELETE", adminEndpoints.productVariantById],
  ["createHsnCode", "POST", adminEndpoints.hsnCodes],
  ["listHsnCodes", "GET", adminEndpoints.hsnCodes],
  ["getHsnCode", "GET", adminEndpoints.hsnCodeByCode],
  ["updateHsnCode", "PATCH", adminEndpoints.hsnCodeByCode],
  ["deleteHsnCode", "DELETE", adminEndpoints.hsnCodeByCode],
  ["createGeography", "POST", adminEndpoints.geography],
  ["listGeography", "GET", adminEndpoints.geography],
  ["getGeography", "GET", adminEndpoints.geographyByCode],
  ["updateGeography", "PATCH", adminEndpoints.geographyByCode],
  ["deleteGeography", "DELETE", adminEndpoints.geographyByCode],
  ["createContentPage", "POST", adminEndpoints.contentPages],
  ["listContentPages", "GET", adminEndpoints.contentPages],
  ["getContentPage", "GET", adminEndpoints.contentPageBySlug],
  ["updateContentPage", "PATCH", adminEndpoints.contentPageBySlug],
  ["deleteContentPage", "DELETE", adminEndpoints.contentPageBySlug],
];

export const sellerApiMap = [
  ["submitOnboardingKyc", "POST", sellerEndpoints.onboardingKyc],
  ["updateOnboardingProfile", "PATCH", sellerEndpoints.onboardingProfile],
  ["reviewSellerKyc", "PATCH", sellerEndpoints.reviewKyc],
  ["getSellerStatus", "GET", sellerEndpoints.status],
  ["listSellerTracking", "GET", sellerEndpoints.tracking],
  ["getSellerTrackingDetail", "GET", sellerEndpoints.trackingOrder],
  ["getSellerProfile", "GET", sellerEndpoints.profile],
  ["updateSellerProfile", "PATCH", sellerEndpoints.profile],
  ["updateBusinessAddress", "PATCH", sellerEndpoints.businessAddress],
  ["updatePickupAddress", "PATCH", sellerEndpoints.pickupAddress],
  ["updateBankDetails", "PATCH", sellerEndpoints.bankDetails],
  ["updateMoreInfo", "PATCH", sellerEndpoints.moreInfo],
  ["updateSettings", "PATCH", sellerEndpoints.settings],
  ["sellerDashboard", "GET", sellerEndpoints.dashboard],
  ["createSellerSubAdmin", "POST", sellerEndpoints.subAdmins],
  ["listSellerSubAdmins", "GET", sellerEndpoints.subAdmins],
  ["updateSellerSubAdminModules", "PATCH", sellerEndpoints.subAdminModules],
];

export const sellerCommissionApiMap = [
  ["myCommissions", "GET", sellerCommissionEndpoints.myCommissions],
  ["myPayouts", "GET", sellerCommissionEndpoints.myPayouts],
  ["calculateOrderCommission", "POST", sellerCommissionEndpoints.calculate],
  ["processBatchPayouts", "POST", sellerCommissionEndpoints.processPayouts],
  ["viewSettlements", "GET", sellerCommissionEndpoints.settlements],
];
